name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot App on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clone repo if not already present
            if [ ! -d "/home/${{ secrets.EC2_USER }}/spring-petclinic" ]; then
              git clone https://github.com/CloudSmith-Agent-Benchmark/spring-petclinic.git
            fi
            cd spring-petclinic
            git fetch --all
            git reset --hard origin/main
            # Build the project
            ./mvnw clean package -DskipTests
          
      - name: Restart Spring Boot App on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 600s
          script: |
            cd spring-petclinic
            # Start the new jar
            nohup java -Djava.net.preferIPv4Stack=true -Dserver.address=0.0.0.0 -jar target/*.jar & disown
